project:
  type: website

website:
  comments: 
    hypothesis: 
      theme: clean
      openSidebar: false
  title: "Steven Howley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

